---
title: "learning"
author: "Asbjørn Kloppenborg"
format: html
editor: visual
---

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics) # Here we refer to the object lipidomics in the _target file
```

## Results

```{r}
targets::tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

```{r}
tar_read(fig_metabolite_distribution)
```

## Building the model

```{r}
log_reg_specs <- logistic_reg() %>%
  set_engine("glm")
log_reg_specs
```

## Pivot data into a wide format

```{r}
lipidomics %>%
  column_values_to_snake_case(metabolite) %>%
  pivot_wider(
    names_from = metabolite,
    values_from = value,
    values_fn = mean,
    names_prefix = "metabolite_"
  )
```

Make a function for the pivot wider part

```{r}
#' Function to pivot lipidomics data from long into wide, using snakecase formated column names
#'
#' @param data Lipidomics
#'
#' @return A wide data frame with 1 obs for each participants

metabolites_to_wider <- function(data) {
    data %>% 
        tidyr::pivot_wider(
            names_from = metabolite,
            values_from = value,
            values_fn = mean,
            names_prefix = "metabolite_")
}
testing_data %>% metabolites_to_wider()
```
